[build-system]
requires = ['setuptools==63.4.3']
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = [".", "mfpml"]
minversion = "6.0"
addopts = "--strict-markers"
testpaths = [
    "tests"
]
markers = [
    "smoke"
]